image: inanimate/packer-ansible
stages:
    - test
    - deploy

test-ansible:
    stage: test
    script:
    - ansible-playbook --version
    - ansible-playbook --syntax-check ansible/setup.yml

test-packer:
    stage: test
    script:
    - packer version
    - packer validate packer/main.json

deploy:
    stage: deploy
    script:
    - apk add git
    - git status
