image: chataro0/packer-ansible:latest
stages:
    - test
    - deploy

verify:
    stage: test
    script:
    - env | grep -i aws
    - ansible-playbook --version
    - ansible-playbook --syntax-check ansible/setup.yml
    - packer version
    - packer validate packer/main.json

deploy:
    stage: deploy
    script:
    - packer build packer/main.json
